default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: find_me_free_wifi_development

test:
  <<: *default
  database: find_me_free_wifi_test

production:
  <<: *default
  database: find_me_free_wifi_production
  username: 
  password: 
